#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Climbs of Colorado: Web-scraping Mountain Project', url: 'climbs_of_colorado'}
- {name: 'Land Cover Classification using a Deep Neural Network', url: 'ml_classify_project_tensor'}
- {name: 'Timeseries using Google Earth Engine', url: 'glca_landsat_timeseries'}
- {name: 'College Campus Maps using PrettyMaps', url: 'campus_prettymaps'}

#-------------------------------
# Medium Section
blog:
- {name: 'Grow your GIS career by showing your work', url: 'https://medium.com/@abreunig9/grow-your-gis-career-by-showing-your-work-a307539bac46'}
- {name: 'GIS Analysts need to learn to code', url: 'https://medium.com/@abreunig9/gis-analysts-need-to-learn-to-code-598975e12c0'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/austinventuress'}
- {icon: 'github',    link: 'https://github.com/austinbreunig'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/austinbreunig'}
- {icon: 'envelope',  link: 'mailto:mailto:abreunig9@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
